# Generated by Django 5.0.4 on 2024-05-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmessage',
            name='number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Номер телефона'),
        ),
    ]
