# Generated by Django 5.0.4 on 2024-05-08 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='ФИО', max_length=255, verbose_name='ФИО')),
                ('exp', models.CharField(default='Стаж', max_length=255, verbose_name='Стаж')),
                ('img', models.URLField(verbose_name='Фото')),
                ('desc', models.TextField(default='Описание', verbose_name='Описание')),
                ('role', models.CharField(default='Роль', max_length=255, verbose_name='Должность')),
                ('education', models.TextField(default='Образование', verbose_name='Образование')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Зоголовок', max_length=255, verbose_name='Заголовок')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.mentor')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
