# Generated by Django 5.0.4 on 2024-05-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='active_courses',
        ),
        migrations.AddField(
            model_name='mentor',
            name='active_courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
