# Generated by Django 5.0.4 on 2024-05-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_remove_mentor_active_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learnedcourse',
            options={'verbose_name': 'Преподаваемая дисциплина', 'verbose_name_plural': 'Преподаваемые дисциплины'},
        ),
        migrations.AlterField(
            model_name='learnedcourse',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='desc',
            field=models.TextField(verbose_name='Награды'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='exp',
            field=models.IntegerField(verbose_name='Стаж'),
        ),
    ]
