# Generated by Django 5.0.6 on 2024-05-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_alter_learnedcourse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnedcourse',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='learnedcourse',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='learnedcourse',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='desc_en',
            field=models.TextField(null=True, verbose_name='Награды'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='desc_kk',
            field=models.TextField(null=True, verbose_name='Награды'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='desc_ru',
            field=models.TextField(null=True, verbose_name='Награды'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='education_en',
            field=models.TextField(null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='education_kk',
            field=models.TextField(null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='education_ru',
            field=models.TextField(null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='role_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='role_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='role_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
