# Generated by Django 5.0.4 on 2024-05-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Название', max_length=255, verbose_name='Название')),
                ('desc', models.TextField(default='Описание', verbose_name='Описание')),
                ('img', models.URLField(verbose_name='Изображение')),
                ('format', models.CharField(default='Формат', max_length=50, verbose_name='Формат')),
                ('startDate', models.DateField(verbose_name='Дата начала')),
                ('startTime', models.TimeField(verbose_name='Время начала')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания события')),
            ],
            options={
                'verbose_name': 'Анонс',
                'verbose_name_plural': 'Анонсы',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='ФИО', max_length=255, verbose_name='ФИО')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='events.event')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
    ]
