# Generated by Django 5.0.4 on 2024-05-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('mentors', '0003_remove_mentor_active_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active_mentors',
            field=models.ManyToManyField(blank=True, to='mentors.mentor'),
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
