# Generated by Django 5.0.4 on 2024-05-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_active_mentors_delete_mentor'),
        ('mentors', '0004_alter_learnedcourse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='active_mentors',
            field=models.ManyToManyField(blank=True, to='mentors.mentor', verbose_name='Ответственные тренеры'),
        ),
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(max_length=50, verbose_name='Формат мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
