# Generated by Django 5.0.6 on 2024-05-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_active_mentors_alter_event_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='desc_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='desc_kk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='desc_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='format_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Формат мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='format_kk',
            field=models.CharField(max_length=50, null=True, verbose_name='Формат мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='format_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Формат мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
