# Generated by Django 5.0.4 on 2024-05-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.URLField(verbose_name='Изображение (1330x600)'),
        ),
    ]
