# Generated by Django 5.0.4 on 2024-05-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_theme_program_alter_features_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
